baseURL: /
languageCode: en-us
title: Catnap's Art Site
theme: ["PaperMod", "hugo-shortcode-gallery"]

enableGitInfo: true

params:
  defaultTheme: dark
  disableThemeToggle: true
  ShowBreadCrumbs: true
  profileMode:
    enabled: true
    title: "<Title>"
    subtitle: "Hi! I'm catnap, an NSFW artist, animator and lewd dude doodler."
    imageUrl: "/avatar.png"
    imageTitle: "Catnapstar"

  socialIcons:
    - name: "Twitter"
      url: "https://twitter.com/catnapstar"
    - name: "Itaku"
      url: "https://itaku.ee/profile/catnapstar"
    - name: "Bluesky"
      url: "https://bsky.app/profile/catnapstar.bsky.social"
    - name: "Patreon"
      url: "https://patreon.com/catnapstar"
